const CHAPTERS = [
  {
    "id": "sikkim",
    "title": "Sikkim",
    "subtitle": "Eastern Himalaya — active rockfall, debris slides and deformation monitoring",
    "center": [
      27.4,
      88.4
    ],
    "zoom": 9,
    "sites": [
      {
        "code": "Ls81",
        "state": "Sikkim",
        "district": "East Sikkim",
        "area": "Chandmari",
        "lat": 27.3389,
        "lon": 88.6065,
        "type": "Deepsheeted creep landslide",
        "date": null,
        "time": null,
        "note": "shallow mudslides + tow cutting by river",
        "photo": "images/ls81_chandmari.jpg",
        "caption": "Crown of the Chandmari landslide scarp, East Sikkim — fractured slope material exposed above the settlement."
      },
      {
        "code": "Ls82",
        "state": "Sikkim",
        "district": "Noth Sikkim",
        "area": "Mangan bazaar",
        "lat": 27.52,
        "lon": 88.53,
        "type": "Deepsheeted creep landslide",
        "date": null,
        "time": null,
        "note": "shallow mudslides + tow cutting by river",
        "photo": "placeholder"
      },
      {
        "code": "Ls83",
        "state": "Sikkim",
        "district": "South Sikkim",
        "area": "Phantam Village Landslie",
        "lat": 27.390313,
        "lon": 88.363437,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": null,
        "photo": "images/ls83_phantam.jpg",
        "caption": "Phantam Village landslide, South Sikkim — debris track running through terraced agricultural land."
      },
      {
        "code": "Ls84",
        "state": "Sikkim",
        "district": "South Sikkim",
        "area": "Namchi District",
        "lat": 27.296944444444446,
        "lon": 88.39555555555556,
        "type": "Active Landslide-cum-Rockfalls",
        "date": "01 Jul 2022",
        "time": "Active",
        "note": null,
        "photo": "images/ls84_namchi.jpg",
        "caption": "Geophone-based Deformation and Early-warning Platform (DEP) installed at Namchi, South Sikkim, as part of the active monitoring network."
      }
    ]
  },
  {
    "id": "kottayam",
    "title": "Kerala — Kottayam (2021)",
    "subtitle": "Debris slides triggered by the October 2021 extreme rainfall event",
    "center": [
      9.58,
      76.9
    ],
    "zoom": 11,
    "sites": [
      {
        "code": "Ls85",
        "state": "Kerala",
        "district": "Kottayam",
        "area": "Poovanchi",
        "lat": 9.572667,
        "lon": 76.886944,
        "type": "Debris slide",
        "date": "17 Oct 2021",
        "time": null,
        "note": "Debris slide",
        "photo": "images/ls85_poovanchi.jpg",
        "caption": "Debris slide scar at Poovanchi, Kottayam — one of five sites mapped after the October 2021 Kerala rainfall event."
      },
      {
        "code": "Ls86",
        "state": "Kerala",
        "district": "Kottayam",
        "area": "Kuttikal Pallapaly road",
        "lat": 9.605332,
        "lon": 76.814438,
        "type": "Debris slide",
        "date": "17 Oct 2021",
        "time": null,
        "note": "Debris slide",
        "photo": "images/ls86_kuttikal.jpg",
        "caption": "Debris slide along the Kuttikal–Pallapally road, Kottayam, showing slope failure adjacent to the carriageway."
      },
      {
        "code": "Ls87",
        "state": "Kerala",
        "district": "Kottayam",
        "area": "Chennappara , Kuppakayam\n",
        "lat": 9.499753,
        "lon": 76.951029,
        "type": "Debris slide",
        "date": "17 Oct 2021",
        "time": null,
        "note": "Debris slide",
        "photo": "placeholder"
      },
      {
        "code": "Ls88",
        "state": "Kerala",
        "district": "Kottayam",
        "area": "Vadakkemala Hills",
        "lat": 9.616636,
        "lon": 76.902644,
        "type": "Debris slide",
        "date": "17 Oct 2021",
        "time": null,
        "note": "Debris slide",
        "photo": "placeholder"
      },
      {
        "code": "Ls89",
        "state": "Kerala",
        "district": "Kottayam",
        "area": "Ward 2, Vadakkemala, Yendayar, Mukkulam\n",
        "lat": 9.613618,
        "lon": 76.903979,
        "type": "Debris slide",
        "date": "17 Oct 2021",
        "time": null,
        "note": "Debris slide",
        "photo": "placeholder"
      }
    ]
  },
  {
    "id": "wayanad2019",
    "title": "Kerala — Wayanad & Malappuram (2019)",
    "subtitle": "The 8 August 2019 debris flow disasters at Puthumala and Kavalapara",
    "center": [
      11.45,
      76.18
    ],
    "zoom": 10,
    "sites": [
      {
        "code": "Ls90",
        "state": "Kerala",
        "district": "Wayanad",
        "area": "Puthumala area",
        "lat": 11.497891666666666,
        "lon": 76.1298861111111,
        "type": "Debris flow",
        "date": "8th August 2019",
        "time": "16:00:00",
        "note": null,
        "photo": "placeholder"
      },
      {
        "code": "Ls91",
        "state": "Kerala",
        "district": "Mallapuram",
        "area": "Kavalapara",
        "lat": 11.409216666666667,
        "lon": 76.23643333333334,
        "type": "Debris flow",
        "date": "8th August 2019",
        "time": "20:00:00",
        "note": null,
        "photo": "placeholder"
      }
    ]
  },
  {
    "id": "chooralmala",
    "title": "Kerala — Chooralmala & Mundakkai (2024)",
    "subtitle": "The 30 July 2024 Wayanad landslide disaster",
    "center": [
      11.4925,
      76.1208
    ],
    "zoom": 13,
    "sites": [
      {
        "code": "Ls93",
        "state": "Kerala",
        "district": "Wayanad",
        "area": "Chooralmala / Mundakkai",
        "lat": 11.4925,
        "lon": 76.1208,
        "type": "Catastrophic debris flow",
        "date": "30 Jul 2024",
        "time": "01:30 - 04:10",
        "note": "One of the most destructive landslide disasters in Kerala's history, with multiple debris flow waves destroying Mundakkai and Chooralmala villages.",
        "photo": "images/ls93_chooralmala.jpg",
        "caption": "Debris fan of the 30 July 2024 Chooralmala-Mundakkai landslide, Wayanad."
      }
    ]
  },
  {
    "id": "munnar",
    "title": "Kerala — Munnar, Idukki",
    "subtitle": "Long-term instrumentation: deformation and rainfall monitoring station",
    "center": [
      10.0889,
      77.0595
    ],
    "zoom": 12,
    "sites": [
      {
        "code": "DEP-MNR",
        "state": "Kerala",
        "district": "Idukki",
        "area": "Munnar (Western Ghats)",
        "lat": 10.0889,
        "lon": 77.0595,
        "type": "Instrumented monitoring station",
        "date": null,
        "time": null,
        "note": "Permanent Deformation and Early-warning Platform (DEP) with rainfall gauge, deployed to monitor slope behaviour in the Western Ghats.",
        "photo": "images/munnar_deployment.jpg",
        "caption": "Completed Deformation and Early-warning Platform (DEP) on a monitored slope in Munnar, Western Ghats."
      }
    ]
  },
  {
    "id": "kodagu",
    "title": "Karnataka — Kodagu",
    "subtitle": "Twelve landslide sites mapped across the Kodagu coffee-growing hills",
    "center": [
      12.4,
      75.7
    ],
    "zoom": 10,
    "sites": [
      {
        "code": "Ls64",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Office of the District Magistrate, Madikeri\n",
        "lat": 12.417159,
        "lon": 75.740538,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls64_madikeri.jpg",
        "caption": "Slope failure at the DC office compound, Madikeri — debris scar on the hill behind the Commissioner's office."
      },
      {
        "code": "Ls65",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Chamundeshwari Nagar",
        "lat": 12.41689,
        "lon": 75.729469,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls65_chamundeshwari.jpg",
        "caption": "Debris slide scar at Chamundeshwari Nagar, Madikeri — house damaged in the 2018 event visible at the toe."
      },
      {
        "code": "Ls66",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Stone hill",
        "lat": 12.428188,
        "lon": 75.715964,
        "type": "Debrisflow",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls66_stonehill.jpg",
        "caption": "Stone hill slope failure, Kodagu — road-adjacent debris deposit with exposed weathered gneiss."
      },
      {
        "code": "Ls67",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Udayagiri Landslide",
        "lat": 12.452847,
        "lon": 75.758041,
        "type": "Debrisflow",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls67_udayagiri.jpg",
        "caption": "Udayagiri landslide, Makkandur — two adjacent slides with blocked stream channel at run-out zone."
      },
      {
        "code": "Ls68",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Makandoor Landside",
        "lat": 12.478959,
        "lon": 75.766769,
        "type": "Debrisflow",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls68_makandoor.jpg",
        "caption": "Makandoor slope failure — sub-parallel ground cracks on the upper slope above destroyed house."
      },
      {
        "code": "Ls69",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Devasthur Cracks",
        "lat": 12.484478,
        "lon": 75.739475,
        "type": "Potental landslide with huge cracks",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls69_devasthur.jpg",
        "caption": "Ground cracks at Devasthur ridge — 1.5 m wide tension crack sinking annually during monsoon."
      },
      {
        "code": "Ls70",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Aimangala",
        "lat": 12.20291,
        "lon": 75.808649,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Shallow debris slides",
        "photo": "images/ls70_aimangala.jpg",
        "caption": "Field photograph from Aimangala area, Kodagu — shallow debris slide scar on the coffee-plantation slope."
      },
      {
        "code": "Ls71",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Nehru Nagar",
        "lat": 12.195171,
        "lon": 75.814431,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Shallow debris slides",
        "photo": "images/ls71_nehrungr.jpg",
        "caption": "Slope damage near Nehru Nagar, Virajpet — creep movement affecting road and adjacent structures."
      },
      {
        "code": "Ls72",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Thora village",
        "lat": 12.164566,
        "lon": 75.709245,
        "type": "Debris slide/ talus faliure",
        "date": null,
        "time": null,
        "note": "Shallow Debrisflow",
        "photo": "images/ls72_thora.jpg",
        "caption": "Field view of the Thora area failure, Kodagu — talus material exposed below a debris slide track."
      },
      {
        "code": "Ls73",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "National Highway 275",
        "lat": 12.443463,
        "lon": 75.683413,
        "type": "Debrisflow",
        "date": null,
        "time": null,
        "note": "Shallow landslides",
        "photo": "placeholder"
      },
      {
        "code": "Ls74",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "National Highway 275",
        "lat": 12.43875,
        "lon": 75.667552,
        "type": "Shallow Debrisflow",
        "date": null,
        "time": null,
        "note": "Shallow landslides",
        "photo": "placeholder"
      },
      {
        "code": "Ls75",
        "state": "Karnataka",
        "district": "Kodagu",
        "area": "Talakkāvēri",
        "lat": 12.3854912,
        "lon": 75.4934296,
        "type": "Debrisflow",
        "date": null,
        "time": null,
        "note": "Shallow mudslides",
        "photo": "placeholder"
      }
    ]
  },
  {
    "id": "uttarakhand",
    "title": "Uttarakhand — Joshimath & Nainital",
    "subtitle": "Field investigation, November 2022 — subsidence, tunnel disaster debris and lake-catchment landslides",
    "center": [
      30.0,
      79.4
    ],
    "zoom": 8,
    "team_photo": "images/team_uttarakhand.jpg",
    "sites": [
      {
        "code": "Ls58",
        "state": "Uttarakhand",
        "district": "Rudraprayag",
        "area": "Joshimath (Ravigram, Sunil, and Gandhinagar)",
        "lat": 30.55527777777778,
        "lon": 79.55305555555556,
        "type": "Deep sheeted active  land subsidance creating cracks into multiples houses",
        "date": null,
        "time": null,
        "note": "Rockfall cum debris slides",
        "photo": "images/ls58_joshimath.jpg",
        "caption": "Subsidence-related cracking in a residential structure at Joshimath — surface manifestation of deep-seated slope deformation."
      },
      {
        "code": "Ls59",
        "state": "Uttarakhand",
        "district": "Rudraprayag",
        "area": "NTPC Tunnel area",
        "lat": 30.493083333333335,
        "lon": 79.62638888888888,
        "type": "Debris runout and flooding led tow cuttings ",
        "date": null,
        "time": null,
        "note": "Rockfall cum debris slides",
        "photo": "images/ls59_ntpc.jpg",
        "caption": "Debris and damaged infrastructure at the NTPC Tapovan-Vishnugad tunnel site following the Feb 2021 Chamoli disaster."
      },
      {
        "code": "Ls60",
        "state": "Uttarakhand",
        "district": "Rudraprayag",
        "area": "Raini Gauv area",
        "lat": 26.19086,
        "lon": 91.79399,
        "type": "Avalanch led debris runout ",
        "date": "7 Feb, 2021 onwards",
        "time": null,
        "note": "Shallow Debis slide",
        "photo": "images/ls60_raini.jpg",
        "caption": "Debris flow channel near Raini village, upstream of the Rishiganga valley, active since the 7 Feb 2021 event."
      },
      {
        "code": "Ls61",
        "state": "Uttarakhand",
        "district": "Rudraprayag",
        "area": "Kunjhethi Landslide",
        "lat": 30.557876,
        "lon": 79.086394,
        "type": "Debris slide",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls61_kunjhethi.jpg",
        "caption": "Slope failure at Kunjhethi affecting adjacent residential structures."
      },
      {
        "code": "Ls62",
        "state": "Uttarakhand",
        "district": "Nainital",
        "area": "Balia nala",
        "lat": 29.37366,
        "lon": 79.4654,
        "type": "Active large Debris slide",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls62_balia.jpg",
        "caption": "Aerial view of the Balia Nala landslide scar above Nainital town, draining toward Naini Lake."
      },
      {
        "code": "Ls63",
        "state": "Uttarakhand",
        "district": "Nainital",
        "area": "DSB College Landslide",
        "lat": 29.3839325,
        "lon": 79.4596705,
        "type": "Debrisflow",
        "date": null,
        "time": null,
        "note": "Shallow Debris slide",
        "photo": "images/ls63_dsb.jpg",
        "caption": "Terraced slope below DSB College, Nainital, showing the broader landslide-prone hillside."
      }
    ]
  },
  {
    "id": "odisha",
    "title": "Odisha — Gajapati",
    "subtitle": "Field investigation, February 2024 — five sites across the Gajapati hill ranges",
    "center": [
      19.02,
      84.2
    ],
    "zoom": 10,
    "sites": [
      {
        "code": "Ls76",
        "state": "Odisha",
        "district": "Gajapati",
        "area": "Parajee Village \n",
        "lat": 19.057675,
        "lon": 84.17931666666667,
        "type": "Rockfall cum debris slides",
        "date": null,
        "time": null,
        "note": "Shallow mudslides",
        "photo": "images/ls76_parajee.jpg",
        "caption": "Field team inspecting a roadside rockfall and debris accumulation near Parajee village, Gajapati."
      },
      {
        "code": "Ls77",
        "state": "Odisha",
        "district": "Gajapati",
        "area": "NH 326A ",
        "lat": 19.0388933,
        "lon": 84.1152533,
        "type": "Debris cum mudslide",
        "date": null,
        "time": null,
        "note": "Shallow mudslides",
        "photo": "images/ls77_nh326a.jpg",
        "caption": "Slope failure scar along NH 326A, Gajapati district, with vegetation removal exposing the failure surface."
      },
      {
        "code": "Ls78",
        "state": "Odisha",
        "district": "Gajapati",
        "area": "Reggeijhula  Village ",
        "lat": 19.071849,
        "lon": 84.09935,
        "type": "Rockfall cum debris slides",
        "date": null,
        "time": null,
        "note": "Shallow mudslides",
        "photo": "images/ls78_reggeijhula.jpg",
        "caption": "Researcher examining a tension crack in a building foundation near Reggeijhula village."
      },
      {
        "code": "Ls79",
        "state": "Odisha",
        "district": "Gajapati",
        "area": "Madha village",
        "lat": 19.00642,
        "lon": 84.364793,
        "type": "Rockfall cum debris slides",
        "date": null,
        "time": null,
        "note": "Shallow mudslides",
        "photo": "images/ls79_madha.jpg",
        "caption": "Close-up of weathered soil profile and surface erosion at Madha village."
      },
      {
        "code": "Ls80",
        "state": "Odisha",
        "district": "Gajapati",
        "area": "Baraghara Village",
        "lat": 18.957,
        "lon": 84.374,
        "type": "Rockfall cum debris slides",
        "date": null,
        "time": null,
        "note": "Shallow mudslides",
        "photo": "images/ls80_baraghara.jpg",
        "caption": "Granitic hill outcrop overlooking agricultural land near Baraghara village."
      }
    ]
  },
  {
    "id": "tirumala",
    "title": "Andhra Pradesh — Tirumala Hills, Tirupati",
    "subtitle": "Rockfall hazard assessment on the Tirumala ghat road",
    "center": [
      13.6714,
      79.3533
    ],
    "zoom": 12,
    "sites": [
      {
        "code": "Ls29",
        "state": "Andhra Pradesh",
        "district": "Tirupati",
        "area": "Tirumala Hill",
        "lat": 13.671388888888888,
        "lon": 79.35333333333332,
        "type": "Rock falls",
        "date": null,
        "time": null,
        "note": "Debrisflow",
        "photo": "images/ls29_tirumala.jpg",
        "caption": "Foliated rock slope prone to rockfall along the Tirumala Hill ghat road, Tirupati, Andhra Pradesh."
      }
    ]
  },
  {
    "id": "mizoram",
    "title": "Mizoram — Multi-District Survey (2026)",
    "subtitle": "Eleven landslide sites across Aizawl, Saitual, Khawzawl, Mamit and Lawngtlai districts",
    "center": [
      23.2,
      92.75
    ],
    "zoom": 8,
    "sites": [
      {
        "code": "Ls94",
        "state": "Mizoram",
        "district": "Aizawl",
        "area": "Bawngkawn — NH108 Rockfall Site",
        "lat": 23.745,
        "lon": 92.722,
        "type": "Rockfall",
        "date": "Mar 2026",
        "time": null,
        "note": "Rockfall-prone road cut along NH108 near Bawngkawn endangering traffic corridor and buildings.",
        "photo": "images/ls94_aizawl_bawngkawn.jpg",
        "caption": "Fractured road-cut slope at Bawngkawn (NH108), Aizawl — overhanging rock blocks posing immediate rockfall hazard."
      },
      {
        "code": "Ls95",
        "state": "Mizoram",
        "district": "Aizawl",
        "area": "Chaltlang — State Highway Rockfall",
        "lat": 23.738,
        "lon": 92.712,
        "type": "Rockfall",
        "date": "Mar 2026",
        "time": null,
        "note": "Structurally controlled rockfall along Chaltlang–Laipuitlang Road; root-induced crack widening observed.",
        "photo": "images/ls95_aizawl_chaltlang.jpg",
        "caption": "Splintery rock face at Chaltlang, Aizawl — vegetation-induced crack widening on the exposed sandstone–shale cut."
      },
      {
        "code": "Ls96",
        "state": "Mizoram",
        "district": "Aizawl",
        "area": "Durtlang Leitan — State Highway Rockfall",
        "lat": 23.752,
        "lon": 92.705,
        "type": "Rockfall",
        "date": "Mar 2026",
        "time": null,
        "note": "Steep road-cut with intersecting joints; existing retaining wall and wire mesh present but drainage weep holes blocked.",
        "photo": "images/ls96_aizawl_durtlang.jpg",
        "caption": "Steep road-cut at Durtlang Leitan, Aizawl — blocky sandstone-shale slope with partial wire mesh protection."
      },
      {
        "code": "Ls97",
        "state": "Mizoram",
        "district": "Saitual",
        "area": "Ngopa CHC — Below Community Health Centre",
        "lat": 23.503,
        "lon": 92.893,
        "type": "Debris slide",
        "date": "24 Jun 2025",
        "time": null,
        "note": "Slope failure triggered by intense precipitation; retrogressive tension cracks visible in hospital building floor.",
        "photo": "images/ls97_saitual_ngopa.jpg",
        "caption": "Slope failure scar below Ngopa Community Health Centre, Saitual — road-cut excavation exposed bedding planes."
      },
      {
        "code": "Ls98",
        "state": "Mizoram",
        "district": "Saitual",
        "area": "Kawlkulh to Khawkawn Road Landslide",
        "lat": 23.495,
        "lon": 92.875,
        "type": "Debris slide",
        "date": "Mar 2026",
        "time": null,
        "note": "Structure-dominated landslide triggered by road widening and slope cutting daylighting weak bedding planes.",
        "photo": "images/ls98_saitual_kawlkulh.jpg",
        "caption": "Landslide scar along the Kawlkulh–Khawkawn Road, Saitual — road widening daylighted weak sandstone–shale contacts."
      },
      {
        "code": "Ls99",
        "state": "Mizoram",
        "district": "Khawzawl",
        "area": "Vengtar Street — Khawzawl Subsidence",
        "lat": 23.693,
        "lon": 93.2,
        "type": "Deep-seated creep / subsidence",
        "date": "Ongoing since 2007",
        "time": null,
        "note": "Chronic subsidence zone active since 2007; irrigation well and emergent groundwater indicate hydro-geological drivers.",
        "photo": "images/ls99_khawzawl.jpg",
        "caption": "Subsidence damage at Vengtar Street, Khawzawl — differential settlement cracking in a residential structure."
      },
      {
        "code": "Ls100",
        "state": "Mizoram",
        "district": "Mamit",
        "area": "New Diamond School — Mamit Subsidence",
        "lat": 23.921,
        "lon": 92.483,
        "type": "Deep-seated creep / subsidence",
        "date": "Ongoing (worsened 2024–2025)",
        "time": null,
        "note": "Progressive land subsidence beneath school buildings; highly jointed splintery shale and siltstone substratum.",
        "photo": "images/ls100_mamit_diamond.jpg",
        "caption": "Ground subsidence at New Diamond School, Mamit — cracking and differential settlement in school premises."
      },
      {
        "code": "Ls101",
        "state": "Mizoram",
        "district": "Mamit",
        "area": "Bazar Veng — Mamit Subsidence",
        "lat": 23.918,
        "lon": 92.487,
        "type": "Deep-seated creep / subsidence",
        "date": "Mar 2026",
        "time": null,
        "note": "Extreme ground settlement; complex interplay between weak weathered lithology and deep-seated gravitational slope deformation.",
        "photo": "images/ls101_mamit_bazarveng.jpg",
        "caption": "Extensive settlement cracking in Bazar Veng, Mamit — one of the most acute subsidence zones observed in the survey."
      },
      {
        "code": "Ls102",
        "state": "Mizoram",
        "district": "Mamit",
        "area": "Venghlun Site — Mamit Landslide",
        "lat": 23.912,
        "lon": 92.491,
        "type": "Landslide (non-rainfall triggered)",
        "date": "Jan 2026",
        "time": "~15:00",
        "note": "Landslide occurred mid-January without rainfall trigger; possible deep-seated or wastewater-induced failure.",
        "photo": "images/ls102_mamit_venghlun.jpg",
        "caption": "Landslide scar at Venghlun, Mamit — hillside settlement affected by a non-rainfall-triggered failure in January 2026."
      },
      {
        "code": "Ls92",
        "state": "Mizoram",
        "district": "Lawngtlai",
        "area": "Lawngtlai — Near Petrol Pump",
        "lat": 22.5333,
        "lon": 92.8961,
        "type": "Translational debris slide",
        "date": "2024",
        "time": null,
        "note": "Overburden-controlled translational failure along roadside; LiDAR and drone survey conducted; petrol pump and road at risk.",
        "photo": "images/ls92_lawngtlai.jpg",
        "caption": "Debris-mantled slope failure near the petrol pump, Lawngtlai — translational overburden failure threatening road and infrastructure."
      },
      {
        "code": "Ls103",
        "state": "Mizoram",
        "district": "Lawngtlai",
        "area": "Lawngtlai Bazar Landslide",
        "lat": 22.53,
        "lon": 92.898,
        "type": "Reactivated debris slide",
        "date": "Reactivated 2025 (original 1995)",
        "time": null,
        "note": "Landslide first occurred in 1995, reactivated in 2025 during heavy rainfall; exposed rock scar with ongoing instability.",
        "photo": "images/ls103_lawngtlai_bazar.jpg",
        "caption": "Reactivated 1995 landslide scar at Lawngtlai Bazar — exposed debris slope with visible rockfall potential along the bazar road."
      }
    ]
  },
  {
    "id": "arunachal",
    "title": "Arunachal Pradesh — Itanagar (Extended Database)",
    "subtitle": "28 mapped sites across the Itanagar capital region",
    "center": [
      27.09,
      93.6
    ],
    "zoom": 11,
    "table_only": true,
    "sites": [
      {
        "code": "Ls1",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "C Sector",
        "lat": 27.096666666666664,
        "lon": 93.62472222222222,
        "type": "Shallow Debris slide",
        "date": "15 May 2022",
        "time": null,
        "note": "Avalanch led debris runout ",
        "photo": "images/ls01_csector.jpg",
        "caption": "Road subsidence and cracking in C Sector, Itanagar — slope movement on Middle Siwalik fragile sediments."
      },
      {
        "code": "Ls2",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Landslide 1",
        "lat": 27.095555555555553,
        "lon": 93.62583333333333,
        "type": "Shallow Debris slide",
        "date": "15 May 2022",
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls02_csector2.jpg",
        "caption": "Construction on drainage path in C Sector, Itanagar — multi-storey building blocking natural ephemeral drainage."
      },
      {
        "code": "Ls3",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Donyi Polo Road side",
        "lat": 27.10777777777778,
        "lon": 93.62666666666667,
        "type": "Shallow Debris slide",
        "date": "09 Jul 2020",
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls03_donipolo.jpg",
        "caption": "Debris slide along Donyi Polo Road, Itanagar — road-cut slope failure exposing calcareous Siwalik material."
      },
      {
        "code": "Ls4",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Goputinli",
        "lat": 27.078055555555554,
        "lon": 93.5936111111111,
        "type": "Medium size debris slide (Active)",
        "date": "21 Jun 2021",
        "time": "10 :20 am",
        "note": "Creep Landslide",
        "photo": "images/ls04_goputinli.jpg",
        "caption": "Active debris slide at Goputinli, Itanagar — medium-scale failure with visible tension crack at crown."
      },
      {
        "code": "Ls5",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Zooroad",
        "lat": 27.07638888888889,
        "lon": 93.58777777777777,
        "type": "Medium size debris slide (Active)",
        "date": "17 May 2022",
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls05_zooroad.jpg",
        "caption": "Slope failure at Zoo Road, Itanagar — active debris slide endangering the roadway and adjacent structures."
      },
      {
        "code": "Ls6",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Dokum colony",
        "lat": 27.086666666666666,
        "lon": 93.62166666666666,
        "type": "Creep movement",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls06_dokum.jpg",
        "caption": "Creep movement cracks at Dokum Colony, Itanagar — slow deformation visible in walls and ground."
      },
      {
        "code": "Ls7",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Hill top colony",
        "lat": 27.08611111111111,
        "lon": 93.62638888888888,
        "type": "Creep movement",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls07_hilltop.jpg",
        "caption": "Slope instability at Hill Top Colony, Itanagar — creep movement affecting colonial-era structures."
      },
      {
        "code": "Ls8",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Culvet location",
        "lat": 27.08611111111111,
        "lon": 93.6275,
        "type": "Creep movement",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls08_culvet.jpg",
        "caption": "Culvert location landslide, Itanagar — obstructed drainage contributing to slope saturation."
      },
      {
        "code": "Ls9",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "landslide Doni colony",
        "lat": 27.084444444444443,
        "lon": 93.61694444444444,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls09_donicol.jpg",
        "caption": "Debris slide at Doni Colony, Itanagar — shallow failure exposing Quaternary overburden."
      },
      {
        "code": "Ls10",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Landslide near Minister colony",
        "lat": 27.09861111111111,
        "lon": 93.61333333333333,
        "type": "Need to be further assessed",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls10_minister.jpg",
        "caption": "Slope near Minister Colony, Itanagar — potential failure zone with tension features on the hillside."
      },
      {
        "code": "Ls11",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "landslide  Sanki park",
        "lat": 27.090833333333332,
        "lon": 93.60888888888888,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls11_sankipark.jpg",
        "caption": "Shallow debris slide near Sanki Park, Itanagar — recent scar on the urban hillside."
      },
      {
        "code": "Ls12",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Road sinking",
        "lat": 27.093226,
        "lon": 93.605388,
        "type": "Creep movement",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls12_roadsink.jpg",
        "caption": "Road sinking, Itanagar — creep-induced road deformation on the Siwalik hill slopes."
      },
      {
        "code": "Ls13",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Waii International hotel landslide",
        "lat": 27.104166666666668,
        "lon": 93.6236111111111,
        "type": "Medium size debris slide",
        "date": "10th july 2020",
        "time": "7:am ",
        "note": "Creep Landslide",
        "photo": "images/ls13_waii.jpg",
        "caption": "Waii International Hotel landslide, Itanagar — medium-scale debris slide from July 2020 event."
      },
      {
        "code": "Ls14",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Itanagar naharlalgun road landslide",
        "lat": 27.10388888888889,
        "lon": 93.64305555555556,
        "type": "Creep movement",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls14_naharlalgun.jpg",
        "caption": "Creep movement along the Itanagar–Naharlagun road — cracked retaining structures and road surface."
      },
      {
        "code": "Ls15",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "huge mud slide (Sood)",
        "lat": 27.106944444444444,
        "lon": 93.66111111111111,
        "type": "Creep movement",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls15_sood.jpg",
        "caption": "Mudslide at Sood village, Itanagar — shallow slope failure in a residential area on the hill fringe."
      },
      {
        "code": "Ls16",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Sood village landslide",
        "lat": 27.104166666666668,
        "lon": 93.68166666666667,
        "type": "Shallow mudslides",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls16_soodvil.jpg",
        "caption": "Sood village landslide, Itanagar — shallow mudslide scar on the Siwalik hill slope."
      },
      {
        "code": "Ls17",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Downpress colony multihazard",
        "lat": 27.094805555555553,
        "lon": 93.67750000000001,
        "type": "shallow mudslides + tow cutting by river",
        "date": null,
        "time": null,
        "note": "Creep Landslide",
        "photo": "images/ls17_downpress.jpg",
        "caption": "Multi-hazard scenario at Downpress Colony, Itanagar — slope failure combined with river erosion at the toe."
      },
      {
        "code": "Ls18",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "River side mudslide",
        "lat": 27.081944444444446,
        "lon": 93.66027777777778,
        "type": "shallow mudslides + tow cutting by river",
        "date": null,
        "time": null,
        "note": "Creep movement",
        "photo": "images/ls18_riverside.jpg",
        "caption": "River-side mudslide, Itanagar — lateral erosion by Senki River undercutting the slope base."
      },
      {
        "code": "Ls19",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Mudslide",
        "lat": 27.086388888888887,
        "lon": 93.66777777777779,
        "type": "Shallow mudslides",
        "date": null,
        "time": null,
        "note": "Creep movement",
        "photo": "images/ls19_mudslide.jpg",
        "caption": "Shallow mudslide, Itanagar outskirts — debris tongue extending onto the road below."
      },
      {
        "code": "Ls20",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Mudslide ",
        "lat": 27.121944444444445,
        "lon": 93.7611111111111,
        "type": "Shallow mudslides",
        "date": null,
        "time": null,
        "note": "Creep movement",
        "photo": "images/ls20_mudslide2.jpg",
        "caption": "Shallow mudslide near Itanagar periphery — saturated Quaternary overburden failure."
      },
      {
        "code": "Ls21",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Road side slide , Headward erosion",
        "lat": 27.03721,
        "lon": 93.62478,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Creep movement",
        "photo": "images/ls21_roadslide.jpg",
        "caption": "Road-side slope failure with headward erosion, Itanagar — road cut daylighting weak Siwalik beds."
      },
      {
        "code": "Ls22",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Road side slide ",
        "lat": 27.03129,
        "lon": 93.62289,
        "type": null,
        "date": null,
        "time": null,
        "note": "Creep movement",
        "photo": "images/ls22_roadslide2.jpg",
        "caption": "Road-side slide, Itanagar — exposed reddish silty-sand overburden on a steep road-cut slope."
      },
      {
        "code": "Ls23",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Road side landslide",
        "lat": 27.023805555555555,
        "lon": 93.62208333333332,
        "type": "Shallow landslides",
        "date": null,
        "time": null,
        "note": "Creep movement",
        "photo": "images/ls23_roadls.jpg",
        "caption": "Road-side landslide, Itanagar — shallow failure on the road to Banderdewa."
      },
      {
        "code": "Ls24",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Road side landslide",
        "lat": 27.078611111111112,
        "lon": 93.59333333333333,
        "type": "Shallow mudslides",
        "date": null,
        "time": null,
        "note": "Debris cum mudslide",
        "photo": "images/ls24_roadls2.jpg",
        "caption": "Road-side landslide, Itanagar — shallow mudslide on the Itanagar–Zoo Road corridor."
      },
      {
        "code": "Ls25",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "landslide",
        "lat": 27.10138888888889,
        "lon": 93.67277777777778,
        "type": "Shallow mudslides",
        "date": null,
        "time": null,
        "note": "Debris runout",
        "photo": "images/ls25_landslide.jpg",
        "caption": "Shallow mudslide in the Itanagar capital region — debris accumulation on the road shoulder."
      },
      {
        "code": "Ls26",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "landslide",
        "lat": 27.105555555555558,
        "lon": 93.6825,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Debris runout and flooding led tow cuttings ",
        "photo": "images/ls26_landslide2.jpg",
        "caption": "Shallow debris slide near Itanagar — run-out material deposited on the lower slope and road."
      },
      {
        "code": "Ls27",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Road side landslide",
        "lat": 27.125555555555557,
        "lon": 93.70416666666667,
        "type": "Shallow mudslides",
        "date": null,
        "time": null,
        "note": "Debris slide",
        "photo": "images/ls27_roadls3.jpg",
        "caption": "Road-side landslide near Sood, Itanagar — repeated failure on the fragile Siwalik hill slope."
      },
      {
        "code": "Ls28",
        "state": "Arunachal Pradesh",
        "district": "Itanagar",
        "area": "Road side landslide",
        "lat": 27.154722222222222,
        "lon": 93.73666666666666,
        "type": "Shallow landslides",
        "date": null,
        "time": null,
        "note": "Debris slide/ talus faliure",
        "photo": "images/ls28_roadls4.jpg",
        "caption": "Road-side landslide near Banderdewa — shallow Siwalik overburden failure on the Itanagar periphery."
      }
    ]
  },
  {
    "id": "assam_meghalaya",
    "title": "Assam & Meghalaya (Extended Database)",
    "subtitle": "28 mapped sites across Meghalaya, Haflong, Guwahati and Mahur",
    "center": [
      25.5,
      92.5
    ],
    "zoom": 7,
    "table_only": true,
    "sites": [
      {
        "code": "Ls30",
        "state": "Assam & Meghalaya",
        "district": "Meghalaya",
        "area": "Siju Meghalaya",
        "lat": 25.357158,
        "lon": 90.661929,
        "type": "Debris runout",
        "date": null,
        "time": null,
        "note": "Debrisflow",
        "photo": "images/ls30_siju1.jpg",
        "caption": "Slope failure at Siju, Meghalaya — debris scar on the Achaean basement hill slope."
      },
      {
        "code": "Ls31",
        "state": "Assam & Meghalaya",
        "district": "Meghalaya",
        "area": "Siju Meghalaya",
        "lat": 25.358632,
        "lon": 90.668637,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Debrisflow",
        "photo": "images/ls31_siju2.jpg",
        "caption": "Debris slide at Siju, Meghalaya — road-cut failure with exposed weathered crystalline rock."
      },
      {
        "code": "Ls32",
        "state": "Assam & Meghalaya",
        "district": "Meghalaya",
        "area": "Siju Meghalaya",
        "lat": 25.360911,
        "lon": 90.676512,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Debrisflow",
        "photo": "images/ls32_siju3.jpg",
        "caption": "Third Siju landslide site, Meghalaya — shallow creep and surface erosion on the steep hillside."
      },
      {
        "code": "Ls33",
        "state": "Assam & Meghalaya",
        "district": "Meghalaya",
        "area": "Meghalaya",
        "lat": 25.359535,
        "lon": 90.696495,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Debrisflow",
        "photo": "images/ls33_meg1.jpg",
        "caption": "Slope failure site in Meghalaya — shallow debris slide on the rain-saturated hillside."
      },
      {
        "code": "Ls34",
        "state": "Assam & Meghalaya",
        "district": "Meghalaya",
        "area": "Meghalaya",
        "lat": 25.399779,
        "lon": 90.696599,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Debrisflow",
        "photo": "images/ls34_meg2.jpg",
        "caption": "Landslide site in Meghalaya — saturated overburden failure on the Meghalayan plateau margin."
      },
      {
        "code": "Ls35",
        "state": "Assam & Meghalaya",
        "district": "Meghalaya",
        "area": "Meghalaya",
        "lat": 25.400251,
        "lon": 90.715808,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": null,
        "photo": "images/ls35_meg3.jpg",
        "caption": "Slope failure in Meghalaya — creep movement with visible ground cracking on the hillside."
      },
      {
        "code": "Ls36",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong area",
        "lat": 25.431249,
        "lon": 93.141754,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Debrisflow",
        "photo": "images/ls36_meg4.jpg",
        "caption": "Landslide site in Meghalaya — debris slide on a road-cut slope in the Meghalayan hills."
      },
      {
        "code": "Ls37",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong area",
        "lat": 25.380767,
        "lon": 93.123707,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Deep sheeted active  land subsidance creating cracks into multiples houses",
        "photo": "images/ls37_meg5.jpg",
        "caption": "Slope failure in Meghalaya — shallow failure in residual soil above crystalline basement."
      },
      {
        "code": "Ls38",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.151325,
        "lon": 93.0258,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "photo": "images/ls38_haflong1.jpg",
        "caption": "Deep-seated creep landslide at Haflong, Dima Hasao, Assam — cracking in residential structures above the active slide."
      },
      {
        "code": "Ls39",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.143519,
        "lon": 93.02712,
        "type": "Debrisflow",
        "date": null,
        "time": null,
        "note": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "photo": "images/ls39_haflong2.jpg",
        "caption": "Debris flow track at Haflong, Assam — gully erosion and slope failure on the schist-phyllite terrain."
      },
      {
        "code": "Ls40",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.156138,
        "lon": 93.017206,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "photo": "images/ls40_haflong3.jpg",
        "caption": "Shallow debris slide at Haflong, Assam — disturbed slope material on the hillside above town."
      },
      {
        "code": "Ls41",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.155815,
        "lon": 93.017205,
        "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "date": null,
        "time": null,
        "note": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "photo": "images/ls41_haflong4.jpg",
        "caption": "Creep landslide at Haflong, Assam — slow slope movement causing cracking in buildings."
      },
      {
        "code": "Ls42",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.177294,
        "lon": 93.020924,
        "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "date": null,
        "time": null,
        "note": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "photo": "images/ls42_haflong5.jpg",
        "caption": "Deep-seated active creep landslide, Haflong, Assam — multiple cracked structures on the moving mass."
      },
      {
        "code": "Ls43",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.164474,
        "lon": 92.99761,
        "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "date": null,
        "time": null,
        "note": "Deepsheeted creep landslide",
        "photo": "images/ls43_haflong6.jpg",
        "caption": "Landslide at Haflong, Assam — creep movement affecting houses on the lower hillside."
      },
      {
        "code": "Ls44",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.144128,
        "lon": 93.027782,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Deepsheeted creep landslide",
        "photo": "images/ls44_haflong7.jpg",
        "caption": "Shallow debris slide, Haflong, Assam — road-cut failure with fresh scarp exposed."
      },
      {
        "code": "Ls45",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.163834,
        "lon": 93.021656,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Medium size debris slide",
        "photo": "images/ls45_haflong8.jpg",
        "caption": "Creep landslide at Haflong, Assam — progressive movement visible in tilted walls and fences."
      },
      {
        "code": "Ls46",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.184616,
        "lon": 93.109182,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Medium size debris slide (Active)",
        "photo": "images/ls46_haflong9.jpg",
        "caption": "Creep landslide, Haflong, Assam — slow-moving debris mass with cracked infrastructure."
      },
      {
        "code": "Ls47",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.183872,
        "lon": 93.115405,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Medium size debris slide (Active)",
        "photo": "images/ls47_haflong10.jpg",
        "caption": "Shallow debris slide, Haflong, Assam — fresh failure scar on the saturated hillside."
      },
      {
        "code": "Ls48",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.184039,
        "lon": 93.109946,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Meduim size Debris slides",
        "photo": "images/ls48_haflong11.jpg",
        "caption": "Creep landslide, Haflong, Assam — tension cracks and settlement in road pavement above the slide."
      },
      {
        "code": "Ls49",
        "state": "Assam & Meghalaya",
        "district": "Dima Hasao, Assam",
        "area": "Haflong",
        "lat": 25.296772,
        "lon": 93.137459,
        "type": "Shallow Debris slide",
        "date": null,
        "time": null,
        "note": "Meduim size Debris slides",
        "photo": "images/ls49_haflong12.jpg",
        "caption": "Shallow debris slide, Haflong, Assam — run-out debris affecting the road below."
      },
      {
        "code": "Ls50",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Gauhati",
        "lat": 26.15558,
        "lon": 91.803602,
        "type": "Meduim size Debris slides",
        "date": null,
        "time": null,
        "note": "Meduim size Debris slides",
        "photo": "images/ls50_gauhati1.jpg",
        "caption": "Medium debris slide at Guwahati, Assam — decomposed granite and lateritic overburden exposed on the slope."
      },
      {
        "code": "Ls51",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Jyotinagar",
        "lat": 26.190858,
        "lon": 91.793993,
        "type": "Meduim size Debris slides",
        "date": null,
        "time": null,
        "note": "Need to be further assessed",
        "photo": "images/ls51_jyotinagar1.jpg",
        "caption": "Debris slide at Jyotinagar, Guwahati — 2022 event damaged two houses; rills and gullies visible."
      },
      {
        "code": "Ls52",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Jyotinagar",
        "lat": 26.190854,
        "lon": 91.793985,
        "type": "Meduim size Debris slides",
        "date": null,
        "time": null,
        "note": "Potental landslide with huge cracks",
        "photo": "images/ls52_jyotinagar2.jpg",
        "caption": "Second debris slide at Jyotinagar, Guwahati — potential failure slope with large tension crack."
      },
      {
        "code": "Ls53",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Gauhati",
        "lat": 26.213445,
        "lon": 91.693156,
        "type": "Rockfall",
        "date": null,
        "time": null,
        "note": "Rock falls",
        "photo": "images/ls53_gauhati2.jpg",
        "caption": "Rockfall site at Guwahati, Assam — exposed corestones in decomposed granitic overburden."
      },
      {
        "code": "Ls54",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Gauhati",
        "lat": 26.298775,
        "lon": 91.685765,
        "type": "Creep Landslide",
        "date": null,
        "time": null,
        "note": "Rockfall",
        "photo": "images/ls54_gauhati3.jpg",
        "caption": "Creep landslide at Guwahati, Assam — slow slope movement on the hill fringe of the city."
      },
      {
        "code": "Ls55",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Gauhati",
        "lat": 26.210988,
        "lon": 91.689075,
        "type": "Rockfall",
        "date": null,
        "time": null,
        "note": "Rockfall",
        "photo": "images/ls55_gauhati4.jpg",
        "caption": "Rockfall, Guwahati, Assam — detached boulders from saprolitic lateritic hillside."
      },
      {
        "code": "Ls56",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Saron",
        "lat": 25.183611111111112,
        "lon": 93.11444444444444,
        "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "date": null,
        "time": null,
        "note": "Rockfall cum debris slides",
        "photo": "images/ls56_saron.jpg",
        "caption": "Deep-seated creep landslide at Saron, Dima Hasao, Assam — multiple houses cracked by slope movement."
      },
      {
        "code": "Ls57",
        "state": "Assam & Meghalaya",
        "district": "Assam",
        "area": "Mahur",
        "lat": 25.184722222222224,
        "lon": 93.11055555555555,
        "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
        "date": null,
        "time": null,
        "note": "Rockfall cum debris slides",
        "photo": "images/ls57_mahur.jpg",
        "caption": "Deep-seated creep landslide at Mahur, Dima Hasao, Assam — cracking in structures above the active slide mass."
      }
    ]
  }
];

const ALL_SITES = [
  {
    "code": "Ls81",
    "state": "Sikkim",
    "district": "East Sikkim",
    "area": "Chandmari",
    "lat": 27.3389,
    "lon": 88.6065,
    "type": "Deepsheeted creep landslide",
    "chapter": "sikkim"
  },
  {
    "code": "Ls82",
    "state": "Sikkim",
    "district": "Noth Sikkim",
    "area": "Mangan bazaar",
    "lat": 27.52,
    "lon": 88.53,
    "type": "Deepsheeted creep landslide",
    "chapter": "sikkim"
  },
  {
    "code": "Ls83",
    "state": "Sikkim",
    "district": "South Sikkim",
    "area": "Phantam Village Landslie",
    "lat": 27.390313,
    "lon": 88.363437,
    "type": "Creep Landslide",
    "chapter": "sikkim"
  },
  {
    "code": "Ls84",
    "state": "Sikkim",
    "district": "South Sikkim",
    "area": "Namchi District",
    "lat": 27.296944444444446,
    "lon": 88.39555555555556,
    "type": "Active Landslide-cum-Rockfalls",
    "chapter": "sikkim"
  },
  {
    "code": "Ls85",
    "state": "Kerala",
    "district": "Kottayam",
    "area": "Poovanchi",
    "lat": 9.572667,
    "lon": 76.886944,
    "type": "Debris slide",
    "chapter": "kottayam"
  },
  {
    "code": "Ls86",
    "state": "Kerala",
    "district": "Kottayam",
    "area": "Kuttikal Pallapaly road",
    "lat": 9.605332,
    "lon": 76.814438,
    "type": "Debris slide",
    "chapter": "kottayam"
  },
  {
    "code": "Ls87",
    "state": "Kerala",
    "district": "Kottayam",
    "area": "Chennappara , Kuppakayam\n",
    "lat": 9.499753,
    "lon": 76.951029,
    "type": "Debris slide",
    "chapter": "kottayam"
  },
  {
    "code": "Ls88",
    "state": "Kerala",
    "district": "Kottayam",
    "area": "Vadakkemala Hills",
    "lat": 9.616636,
    "lon": 76.902644,
    "type": "Debris slide",
    "chapter": "kottayam"
  },
  {
    "code": "Ls89",
    "state": "Kerala",
    "district": "Kottayam",
    "area": "Ward 2, Vadakkemala, Yendayar, Mukkulam\n",
    "lat": 9.613618,
    "lon": 76.903979,
    "type": "Debris slide",
    "chapter": "kottayam"
  },
  {
    "code": "Ls90",
    "state": "Kerala",
    "district": "Wayanad",
    "area": "Puthumala area",
    "lat": 11.497891666666666,
    "lon": 76.1298861111111,
    "type": "Debris flow",
    "chapter": "wayanad2019"
  },
  {
    "code": "Ls91",
    "state": "Kerala",
    "district": "Mallapuram",
    "area": "Kavalapara",
    "lat": 11.409216666666667,
    "lon": 76.23643333333334,
    "type": "Debris flow",
    "chapter": "wayanad2019"
  },
  {
    "code": "Ls93",
    "state": "Kerala",
    "district": "Wayanad",
    "area": "Chooralmala / Mundakkai",
    "lat": 11.4925,
    "lon": 76.1208,
    "type": "Catastrophic debris flow",
    "chapter": "chooralmala"
  },
  {
    "code": "DEP-MNR",
    "state": "Kerala",
    "district": "Idukki",
    "area": "Munnar (Western Ghats)",
    "lat": 10.0889,
    "lon": 77.0595,
    "type": "Instrumented monitoring station",
    "chapter": "munnar"
  },
  {
    "code": "Ls64",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Office of the District Magistrate, Madikeri\n",
    "lat": 12.417159,
    "lon": 75.740538,
    "type": "Creep Landslide",
    "chapter": "kodagu"
  },
  {
    "code": "Ls65",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Chamundeshwari Nagar",
    "lat": 12.41689,
    "lon": 75.729469,
    "type": "Creep Landslide",
    "chapter": "kodagu"
  },
  {
    "code": "Ls66",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Stone hill",
    "lat": 12.428188,
    "lon": 75.715964,
    "type": "Debrisflow",
    "chapter": "kodagu"
  },
  {
    "code": "Ls67",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Udayagiri Landslide",
    "lat": 12.452847,
    "lon": 75.758041,
    "type": "Debrisflow",
    "chapter": "kodagu"
  },
  {
    "code": "Ls68",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Makandoor Landside",
    "lat": 12.478959,
    "lon": 75.766769,
    "type": "Debrisflow",
    "chapter": "kodagu"
  },
  {
    "code": "Ls69",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Devasthur Cracks",
    "lat": 12.484478,
    "lon": 75.739475,
    "type": "Potental landslide with huge cracks",
    "chapter": "kodagu"
  },
  {
    "code": "Ls70",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Aimangala",
    "lat": 12.20291,
    "lon": 75.808649,
    "type": "Creep Landslide",
    "chapter": "kodagu"
  },
  {
    "code": "Ls71",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Nehru Nagar",
    "lat": 12.195171,
    "lon": 75.814431,
    "type": "Creep Landslide",
    "chapter": "kodagu"
  },
  {
    "code": "Ls72",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Thora village",
    "lat": 12.164566,
    "lon": 75.709245,
    "type": "Debris slide/ talus faliure",
    "chapter": "kodagu"
  },
  {
    "code": "Ls73",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "National Highway 275",
    "lat": 12.443463,
    "lon": 75.683413,
    "type": "Debrisflow",
    "chapter": "kodagu"
  },
  {
    "code": "Ls74",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "National Highway 275",
    "lat": 12.43875,
    "lon": 75.667552,
    "type": "Shallow Debrisflow",
    "chapter": "kodagu"
  },
  {
    "code": "Ls75",
    "state": "Karnataka",
    "district": "Kodagu",
    "area": "Talakkāvēri",
    "lat": 12.3854912,
    "lon": 75.4934296,
    "type": "Debrisflow",
    "chapter": "kodagu"
  },
  {
    "code": "Ls58",
    "state": "Uttarakhand",
    "district": "Rudraprayag",
    "area": "Joshimath (Ravigram, Sunil, and Gandhinagar)",
    "lat": 30.55527777777778,
    "lon": 79.55305555555556,
    "type": "Deep sheeted active  land subsidance creating cracks into multiples houses",
    "chapter": "uttarakhand"
  },
  {
    "code": "Ls59",
    "state": "Uttarakhand",
    "district": "Rudraprayag",
    "area": "NTPC Tunnel area",
    "lat": 30.493083333333335,
    "lon": 79.62638888888888,
    "type": "Debris runout and flooding led tow cuttings ",
    "chapter": "uttarakhand"
  },
  {
    "code": "Ls60",
    "state": "Uttarakhand",
    "district": "Rudraprayag",
    "area": "Raini Gauv area",
    "lat": 26.19086,
    "lon": 91.79399,
    "type": "Avalanch led debris runout ",
    "chapter": "uttarakhand"
  },
  {
    "code": "Ls61",
    "state": "Uttarakhand",
    "district": "Rudraprayag",
    "area": "Kunjhethi Landslide",
    "lat": 30.557876,
    "lon": 79.086394,
    "type": "Debris slide",
    "chapter": "uttarakhand"
  },
  {
    "code": "Ls62",
    "state": "Uttarakhand",
    "district": "Nainital",
    "area": "Balia nala",
    "lat": 29.37366,
    "lon": 79.4654,
    "type": "Active large Debris slide",
    "chapter": "uttarakhand"
  },
  {
    "code": "Ls63",
    "state": "Uttarakhand",
    "district": "Nainital",
    "area": "DSB College Landslide",
    "lat": 29.3839325,
    "lon": 79.4596705,
    "type": "Debrisflow",
    "chapter": "uttarakhand"
  },
  {
    "code": "Ls76",
    "state": "Odisha",
    "district": "Gajapati",
    "area": "Parajee Village \n",
    "lat": 19.057675,
    "lon": 84.17931666666667,
    "type": "Rockfall cum debris slides",
    "chapter": "odisha"
  },
  {
    "code": "Ls77",
    "state": "Odisha",
    "district": "Gajapati",
    "area": "NH 326A ",
    "lat": 19.0388933,
    "lon": 84.1152533,
    "type": "Debris cum mudslide",
    "chapter": "odisha"
  },
  {
    "code": "Ls78",
    "state": "Odisha",
    "district": "Gajapati",
    "area": "Reggeijhula  Village ",
    "lat": 19.071849,
    "lon": 84.09935,
    "type": "Rockfall cum debris slides",
    "chapter": "odisha"
  },
  {
    "code": "Ls79",
    "state": "Odisha",
    "district": "Gajapati",
    "area": "Madha village",
    "lat": 19.00642,
    "lon": 84.364793,
    "type": "Rockfall cum debris slides",
    "chapter": "odisha"
  },
  {
    "code": "Ls80",
    "state": "Odisha",
    "district": "Gajapati",
    "area": "Baraghara Village",
    "lat": 18.957,
    "lon": 84.374,
    "type": "Rockfall cum debris slides",
    "chapter": "odisha"
  },
  {
    "code": "Ls29",
    "state": "Andhra Pradesh",
    "district": "Tirupati",
    "area": "Tirumala Hill",
    "lat": 13.671388888888888,
    "lon": 79.35333333333332,
    "type": "Rock falls",
    "chapter": "tirumala"
  },
  {
    "code": "Ls94",
    "state": "Mizoram",
    "district": "Aizawl",
    "area": "Bawngkawn — NH108 Rockfall Site",
    "lat": 23.745,
    "lon": 92.722,
    "type": "Rockfall",
    "chapter": "mizoram"
  },
  {
    "code": "Ls95",
    "state": "Mizoram",
    "district": "Aizawl",
    "area": "Chaltlang — State Highway Rockfall",
    "lat": 23.738,
    "lon": 92.712,
    "type": "Rockfall",
    "chapter": "mizoram"
  },
  {
    "code": "Ls96",
    "state": "Mizoram",
    "district": "Aizawl",
    "area": "Durtlang Leitan — State Highway Rockfall",
    "lat": 23.752,
    "lon": 92.705,
    "type": "Rockfall",
    "chapter": "mizoram"
  },
  {
    "code": "Ls97",
    "state": "Mizoram",
    "district": "Saitual",
    "area": "Ngopa CHC — Below Community Health Centre",
    "lat": 23.503,
    "lon": 92.893,
    "type": "Debris slide",
    "chapter": "mizoram"
  },
  {
    "code": "Ls98",
    "state": "Mizoram",
    "district": "Saitual",
    "area": "Kawlkulh to Khawkawn Road Landslide",
    "lat": 23.495,
    "lon": 92.875,
    "type": "Debris slide",
    "chapter": "mizoram"
  },
  {
    "code": "Ls99",
    "state": "Mizoram",
    "district": "Khawzawl",
    "area": "Vengtar Street — Khawzawl Subsidence",
    "lat": 23.693,
    "lon": 93.2,
    "type": "Deep-seated creep / subsidence",
    "chapter": "mizoram"
  },
  {
    "code": "Ls100",
    "state": "Mizoram",
    "district": "Mamit",
    "area": "New Diamond School — Mamit Subsidence",
    "lat": 23.921,
    "lon": 92.483,
    "type": "Deep-seated creep / subsidence",
    "chapter": "mizoram"
  },
  {
    "code": "Ls101",
    "state": "Mizoram",
    "district": "Mamit",
    "area": "Bazar Veng — Mamit Subsidence",
    "lat": 23.918,
    "lon": 92.487,
    "type": "Deep-seated creep / subsidence",
    "chapter": "mizoram"
  },
  {
    "code": "Ls102",
    "state": "Mizoram",
    "district": "Mamit",
    "area": "Venghlun Site — Mamit Landslide",
    "lat": 23.912,
    "lon": 92.491,
    "type": "Landslide (non-rainfall triggered)",
    "chapter": "mizoram"
  },
  {
    "code": "Ls92",
    "state": "Mizoram",
    "district": "Lawngtlai",
    "area": "Lawngtlai — Near Petrol Pump",
    "lat": 22.5333,
    "lon": 92.8961,
    "type": "Translational debris slide",
    "chapter": "mizoram"
  },
  {
    "code": "Ls103",
    "state": "Mizoram",
    "district": "Lawngtlai",
    "area": "Lawngtlai Bazar Landslide",
    "lat": 22.53,
    "lon": 92.898,
    "type": "Reactivated debris slide",
    "chapter": "mizoram"
  },
  {
    "code": "Ls1",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "C Sector",
    "lat": 27.096666666666664,
    "lon": 93.62472222222222,
    "type": "Shallow Debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls2",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Landslide 1",
    "lat": 27.095555555555553,
    "lon": 93.62583333333333,
    "type": "Shallow Debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls3",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Donyi Polo Road side",
    "lat": 27.10777777777778,
    "lon": 93.62666666666667,
    "type": "Shallow Debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls4",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Goputinli",
    "lat": 27.078055555555554,
    "lon": 93.5936111111111,
    "type": "Medium size debris slide (Active)",
    "chapter": "arunachal"
  },
  {
    "code": "Ls5",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Zooroad",
    "lat": 27.07638888888889,
    "lon": 93.58777777777777,
    "type": "Medium size debris slide (Active)",
    "chapter": "arunachal"
  },
  {
    "code": "Ls6",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Dokum colony",
    "lat": 27.086666666666666,
    "lon": 93.62166666666666,
    "type": "Creep movement",
    "chapter": "arunachal"
  },
  {
    "code": "Ls7",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Hill top colony",
    "lat": 27.08611111111111,
    "lon": 93.62638888888888,
    "type": "Creep movement",
    "chapter": "arunachal"
  },
  {
    "code": "Ls8",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Culvet location",
    "lat": 27.08611111111111,
    "lon": 93.6275,
    "type": "Creep movement",
    "chapter": "arunachal"
  },
  {
    "code": "Ls9",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "landslide Doni colony",
    "lat": 27.084444444444443,
    "lon": 93.61694444444444,
    "type": "Shallow Debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls10",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Landslide near Minister colony",
    "lat": 27.09861111111111,
    "lon": 93.61333333333333,
    "type": "Need to be further assessed",
    "chapter": "arunachal"
  },
  {
    "code": "Ls11",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "landslide  Sanki park",
    "lat": 27.090833333333332,
    "lon": 93.60888888888888,
    "type": "Shallow Debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls12",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Road sinking",
    "lat": 27.093226,
    "lon": 93.605388,
    "type": "Creep movement",
    "chapter": "arunachal"
  },
  {
    "code": "Ls13",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Waii International hotel landslide",
    "lat": 27.104166666666668,
    "lon": 93.6236111111111,
    "type": "Medium size debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls14",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Itanagar naharlalgun road landslide",
    "lat": 27.10388888888889,
    "lon": 93.64305555555556,
    "type": "Creep movement",
    "chapter": "arunachal"
  },
  {
    "code": "Ls15",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "huge mud slide (Sood)",
    "lat": 27.106944444444444,
    "lon": 93.66111111111111,
    "type": "Creep movement",
    "chapter": "arunachal"
  },
  {
    "code": "Ls16",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Sood village landslide",
    "lat": 27.104166666666668,
    "lon": 93.68166666666667,
    "type": "Shallow mudslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls17",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Downpress colony multihazard",
    "lat": 27.094805555555553,
    "lon": 93.67750000000001,
    "type": "shallow mudslides + tow cutting by river",
    "chapter": "arunachal"
  },
  {
    "code": "Ls18",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "River side mudslide",
    "lat": 27.081944444444446,
    "lon": 93.66027777777778,
    "type": "shallow mudslides + tow cutting by river",
    "chapter": "arunachal"
  },
  {
    "code": "Ls19",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Mudslide",
    "lat": 27.086388888888887,
    "lon": 93.66777777777779,
    "type": "Shallow mudslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls20",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Mudslide ",
    "lat": 27.121944444444445,
    "lon": 93.7611111111111,
    "type": "Shallow mudslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls21",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Road side slide , Headward erosion",
    "lat": 27.03721,
    "lon": 93.62478,
    "type": "Shallow Debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls22",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Road side slide ",
    "lat": 27.03129,
    "lon": 93.62289,
    "type": null,
    "chapter": "arunachal"
  },
  {
    "code": "Ls23",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Road side landslide",
    "lat": 27.023805555555555,
    "lon": 93.62208333333332,
    "type": "Shallow landslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls24",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Road side landslide",
    "lat": 27.078611111111112,
    "lon": 93.59333333333333,
    "type": "Shallow mudslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls25",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "landslide",
    "lat": 27.10138888888889,
    "lon": 93.67277777777778,
    "type": "Shallow mudslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls26",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "landslide",
    "lat": 27.105555555555558,
    "lon": 93.6825,
    "type": "Shallow Debris slide",
    "chapter": "arunachal"
  },
  {
    "code": "Ls27",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Road side landslide",
    "lat": 27.125555555555557,
    "lon": 93.70416666666667,
    "type": "Shallow mudslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls28",
    "state": "Arunachal Pradesh",
    "district": "Itanagar",
    "area": "Road side landslide",
    "lat": 27.154722222222222,
    "lon": 93.73666666666666,
    "type": "Shallow landslides",
    "chapter": "arunachal"
  },
  {
    "code": "Ls30",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Siju Meghalaya",
    "lat": 25.357158,
    "lon": 90.661929,
    "type": "Debris runout",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls31",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Siju Meghalaya",
    "lat": 25.358632,
    "lon": 90.668637,
    "type": "Shallow Debris slide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls32",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Siju Meghalaya",
    "lat": 25.360911,
    "lon": 90.676512,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls33",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Meghalaya",
    "lat": 25.359535,
    "lon": 90.696495,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls34",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Meghalaya",
    "lat": 25.399779,
    "lon": 90.696599,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls35",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Meghalaya",
    "lat": 25.400251,
    "lon": 90.715808,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls36",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Meghalaya",
    "lat": 25.431249,
    "lon": 93.141754,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls37",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Meghalaya",
    "lat": 25.380767,
    "lon": 93.123707,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls38",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.151325,
    "lon": 93.0258,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls39",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.143519,
    "lon": 93.02712,
    "type": "Debrisflow",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls40",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.156138,
    "lon": 93.017206,
    "type": "Shallow Debris slide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls41",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.155815,
    "lon": 93.017205,
    "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls42",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.177294,
    "lon": 93.020924,
    "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls43",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.164474,
    "lon": 92.99761,
    "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls44",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.144128,
    "lon": 93.027782,
    "type": "Shallow Debris slide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls45",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.163834,
    "lon": 93.021656,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls46",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.184616,
    "lon": 93.109182,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls47",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.183872,
    "lon": 93.115405,
    "type": "Shallow Debris slide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls48",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.184039,
    "lon": 93.109946,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls49",
    "state": "Assam & Meghalaya",
    "district": "Meghalaya",
    "area": "Haflong",
    "lat": 25.296772,
    "lon": 93.137459,
    "type": "Shallow Debris slide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls50",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Gauhati",
    "lat": 26.15558,
    "lon": 91.803602,
    "type": "Meduim size Debris slides",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls51",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Jyotinagar",
    "lat": 26.190858,
    "lon": 91.793993,
    "type": "Meduim size Debris slides",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls52",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Jyotinagar",
    "lat": 26.190854,
    "lon": 91.793985,
    "type": "Meduim size Debris slides",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls53",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Gauhati",
    "lat": 26.213445,
    "lon": 91.693156,
    "type": "Rockfall",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls54",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Gauhati",
    "lat": 26.298775,
    "lon": 91.685765,
    "type": "Creep Landslide",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls55",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Gauhati",
    "lat": 26.210988,
    "lon": 91.689075,
    "type": "Rockfall",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls56",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Saron",
    "lat": 25.183611111111112,
    "lon": 93.11444444444444,
    "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
    "chapter": "assam_meghalaya"
  },
  {
    "code": "Ls57",
    "state": "Assam & Meghalaya",
    "district": "Assam",
    "area": "Mahur",
    "lat": 25.184722222222224,
    "lon": 93.11055555555555,
    "type": "Deep sheeted active creep landslide creating cracks into multiples houses",
    "chapter": "assam_meghalaya"
  }
];
